/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TrabalhoFinal;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        
        Notas notas = new Notas();
        notas.setNomes("Gabriella Cordeiro Almeida");
        notas.setNotas(10.0);
        
        System.out.println(notas);
    }
}
